name: Github CICD

on:
  push:
    branches:
      - sg-server
jobs:
  deploy:
    name: Deploy Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Prepare PEM file
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          mkdir -p _deploy
          echo -e '${{ secrets.SSH_PRIVATE_KEY }}' > _deploy/goingsunny-sg.pem
          chmod 700 _deploy/goingsunny-sg.pem
          ssh-keyscan -t rsa 13.215.51.234 >> ~/.ssh/known_hosts
      - name: Deploy
        run: npm run deploy:sg-server
